# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'ci'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:

jobs:
  # Linting jobs - terraform, go
  terraform_lint:
    uses: 'abcxyz/actions/.github/workflows/terraform-lint.yml@main' # ratchet:exclude
    with:
      directory: 'terraform'
      terraform_version: '1.3'

  yaml_lint:
    uses: 'abcxyz/actions/.github/workflows/yaml-lint.yml@main' # ratchet:exclude

  go_lint:
    uses: 'abcxyz/actions/.github/workflows/go-lint.yml@main' # ratchet:exclude

  # Unit tests - go
  go_test:
    uses: 'abcxyz/actions/.github/workflows/go-test.yml@main' # ratchet:exclude
